[package]
name = "s4n"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "macos")'.dependencies]
git2 = { version = "0.19.0", features = ["vendored-openssl"] }

[target.'cfg(target_os = "windows")'.dependencies]
git2 = { version = "0.19.0" }

[target.'cfg(target_os = "linux")'.dependencies]
git2 = { version = "0.19.0" }

[dependencies]
clap = { version = "4.5.18", features = ["derive", "wrap_help"] }
colored = "2.1.0"
fancy-regex = "0.11.0"
pathdiff = "0.2.1"
rust_xlsxwriter = "0.78.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
serde_yml = "0.0.12"
sha1 = "0.10.6"
shlex = "1.3.0"
slugify = "0.1.0"
syntect = { version = "5.2.0", default-features = false, features = ["default-fancy"] }
sysinfo = "0.32.0"
tempfile = "3.13.0"

[dev-dependencies]
serial_test = "3.1.1"
calamine = "0.25.0"
