[package]
name = "s4n"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive", "wrap_help"] }
colored = "2.1.0"
fancy-regex = "0.11.0"
git2 = { version = "0.19.0", features = ["vendored-openssl"] }
pathdiff = "0.2.1"
rust_xlsxwriter = "0.78.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
serde_yml = "0.0.12"
sha1 = "0.10.6"
shlex = "1.3.0"
slugify = "0.1.0"
syntect = { version = "5.2.0", default-features = false, features = ["regex-fancy", "parsing", "default-themes", "default-syntaxes"] }
sysinfo = "0.32.0"
tempfile = "3.13.0"
whoami = "1.5.2"

[dev-dependencies]
serial_test = "3.1.1"
calamine = "0.25.0"
