[package]
name = "s4n"
description = "SciWIn Client: Reproducible computational Workflows made easy!"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/fairagro/m4.4_sciwin_client"
authors = [
    "Jens Krumsieck",
    "Antonia Leidel",
    "Harald von Waldow",
    "Patrick König",
]

[dependencies]
cwl = { path = "crates/cwl" }
serde = { workspace = true }
serde_yml = { workspace = true }
clap = { version = "4.5.18", features = ["derive", "wrap_help"] }
colored = "2.1.0"
fancy-regex = "0.11.0"
git2 = { version = "0.19.0", features = ["vendored-openssl"] }
pathdiff = "0.2.1"
rand = "0.8.5"
rust_xlsxwriter = "0.78.0"
serde_json = "1.0.132"
sha1 = "0.10.6"
shlex = "1.3.0"
slugify = "0.1.0"
walkdir = "2.5.0"
prettytable-rs = "0.10.0"
tempfile = "3.13.0"
syntect = { version = "5.2.0", default-features = false, features = [
    "regex-fancy",
    "parsing",
    "default-themes",
    "default-syntaxes",
] }
sysinfo = "0.32.0"
urlencoding = "2.1.3"
whoami = "1.5.2"
reqwest = { version = "0.12.9", features = ["json"] }
tokio = { version = "1.42.0", features = ["full"] }
dialoguer = "0.11.0"

[dev-dependencies]
serial_test = "3.1.1"
calamine = "0.25.0"
assert_cmd = "2.0.16"
predicates = "3.1.2"

# Workspace settings
[workspace]
members = ["crates/*", "."]

[workspace.dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_yml = "0.0.12"

# Dist Settings
[profile.dist]
inherits = "release"
lto = "thin"

[package.metadata.wix]
upgrade-guid = "0E96056C-17BE-44EF-B299-12D19B4FFDF4"
path-guid = "4F851203-47E0-4E29-A325-6C14EA33173B"
license = false
eula = false
