[package]
name = "s4n"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
colored = "2.1.0"
git2 = "0.19.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_yml = "0.0.12"
shlex = "1.3.0"
slugify = "0.1.0"
