site_name: SciWin client documentation
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
repo_url: https://github.com/fairagro/m4.4_sciwin_client
repo_name: fairagro/m4.4_sciwin_client
edit_uri: 'blob/main/docs/'
