[package]
name = "cwl-execution"
version = "0.1.0"
edition = "2021"

[dependencies]
cwl = { path = "../cwl" }
log = { workspace = true }
pathdiff = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tempfile = { workspace = true }

fancy-regex = "0.14.0"
rand = "0.8.5"
sysinfo = "0.34.1"
urlencoding = "2.1.3"

[dev-dependencies]
serial_test = "3.1.1"