name: 🏗️ Build and Test
permissions:
  contents: read
  
on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "windows-2025"
          - os: "ubuntu-latest"
          - os: "macos-latest"
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-      
      - name: Setup podman (because docker is shitty on windows runner)
        if: runner.os == 'windows'
        shell: powershell
        run: |
          Stop-Service docker
          choco install podman-cli
          podman machine init
          $Env:DOCKER_HOST = 'npipe:////./pipe/podman-machine-default'
          podman machine start
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
          locked: true
      - name: Build
        run: cargo build --verbose
      - name: Install CWL Tool
        run: pip install cwltool
      - name: Run tests
        run: cargo nextest run
