name: 🏗️ Build and Test

on:
  push:
    branches: ["main", "feature/**"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cleanup residues
        run: cargo clean
      - name: Build
        run: cargo build --verbose
      - name: Install CWL Tool
        run: pip install cwltool
      - name: Run tests
        run: cargo test -- --nocapture
