name: 📎 Clippy
on:
  workflow_call:

jobs:
  clippy_check:
    name: 📎 Check & Fix
    runs-on: ubuntu-latest
    # Make sure CI fails on all warnings, including Clippy lints
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Run Clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets --all-features --workspace
