name: 🦺 Coverage

on:
  push:
    branches: ["main", "feature/**"]
  pull_request:
    branches: ["main"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Tarpaulin 📈
        run: cargo install cargo-tarpaulin  
      - name: Install CWL Tool
        run: pip install cwltool
      - name: Run coverage
        run: cargo tarpaulin --out Xml
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: cobertura.xml
