name: 📖 Deploy user documentation

on:
    push:
        branches:
            - main
        paths:
            - 'docs/**'
            - '.github/workflows/docs.yml'
            - 'mkdocs.yml'
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install mkdocs mkdocs-material

            - name: Build
              run: mkdocs build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                  personal_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./site